name: Automatic test on Push
on: push

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip      
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi      
      - name: Run on BG
        run: |
          python mentoriacompartilhada/manage.py makemigrations
          python mentoriacompartilhada/manage.py migrate
          python mentoriacompartilhada/manage.py runserver 8888 &
          echo $! > app.pid
          sleep 5s
      - name: Run Newman Tests
        uses: matt-ball/newman-action@master
        with:
          collection: test.postman_collection
          environment: test.postman_environment
          iterationCount: 1
          delayRequest: 500